"""Tokeniser-side statistics: Section 4 (CJK round trip) and the appendices
on vocabulary composition and the tokeniser panel.

Computed live from the pinned tokenisers' vocabularies, or summarised from
committed panel runs in data/derived/tokeniser_panel/ (regenerated by the
scripts under experiments/tokenisation/).
"""
from __future__ import annotations

from collections import Counter

import pandas as pd
from scipy import stats as sps

from . import tokenisers as T
from .paths import DATA, TABLES

P = DATA / "derived" / "tokeniser_panel"
SCRIPTS = ["Han", "Kana", "Hangul", "Arabic", "Cyrillic", "Devanagari", "Gujarati", "Tamil", "Latin"]


def script_of(ch: str) -> str | None:
    """Unicode block of one character, for the nine scripts we report."""
    o = ord(ch)
    if 0x4E00 <= o <= 0x9FFF or 0x3400 <= o <= 0x4DBF:
        return "Han"
    if 0x3040 <= o <= 0x30FF:
        return "Kana"
    if 0xAC00 <= o <= 0xD7AF:
        return "Hangul"
    if 0x0600 <= o <= 0x06FF:
        return "Arabic"
    if 0x0400 <= o <= 0x04FF:
        return "Cyrillic"
    if 0x0900 <= o <= 0x097F:
        return "Devanagari"
    if 0x0A80 <= o <= 0x0AFF:
        return "Gujarati"
    if 0x0B80 <= o <= 0x0BFF:
        return "Tamil"
    if ch.isascii() and ch.isalpha():
        return "Latin"
    return None


def vocab_by_script() -> pd.DataFrame:
    """XLM-R vocabulary composition. A piece counts for a script when every
    character we can place belongs to that one script. A single-character
    piece cannot be split, so the share of them bounds how far text in that
    script can be fragmented: this is why CJK has so little headroom."""
    tot, multi, lens = Counter(), Counter(), Counter()
    for piece in T.get("xlmr").get_vocab():
        s = piece.lstrip("▁")
        if not s:
            continue
        sc = {script_of(c) for c in s} - {None}
        if len(sc) != 1:
            continue
        k = sc.pop()
        tot[k] += 1
        multi[k] += len(s) > 1
        lens[k] += len(s)
    rows = [{"script": k, "vocab_tokens": tot[k], "multi_char_tokens": multi[k],
             "mean_token_len": round(lens[k] / tot[k], 2)} for k in SCRIPTS]
    d = pd.DataFrame(rows)
    d["pct_multi_char"] = (100 * d.multi_char_tokens / d.vocab_tokens).round(1)
    d["pct_single_char"] = (100 - d.pct_multi_char).round(1)
    return d


def vocab_sizes() -> pd.DataFrame:
    return pd.DataFrame([{"tokeniser": k, "vocab_size": len(T.get(k))}
                         for k in ["xlmr", "mbert", "mt5", "rembert"]])


def panel_tp_summary() -> pd.DataFrame:
    """Mean token parity per tokeniser, native vs romanised, over five languages."""
    d = pd.read_csv(P / "intrinsic_indicmt.csv")
    rows = []
    for k in ["xlmr", "mt5", "mbert", "byt5", "gpt2"]:
        g = d[d.tokeniser == k]
        nat = g[g.condition == "native"].set_index("lang").tp
        rom = g[g.condition == "romanised"].set_index("lang").tp
        ix = nat.index.intersection(rom.index)
        rows.append({"tokeniser": k, "tp_native_mean": round(float(nat[ix].mean()), 2),
                     "tp_romanised_mean": round(float(rom[ix].mean()), 2),
                     "pct_change_mean": round(float(((rom[ix] - nat[ix]) / nat[ix] * 100).mean()), 1),
                     "tp_native_max": round(float(nat[ix].max()), 1)})
    return pd.DataFrame(rows)


def sampler_uniformity_ks() -> pd.DataFrame:
    """App. Sampler Verification: per-word chi-square p-values of the sampler should be
    uniform under the null; summarised with a KS test and Bonferroni count."""
    rows = []
    for tok, f in [("xlmr", "sampler_uniformity.csv"), ("mt5", "sampler_uniformity_mt5.csv")]:
        d = pd.read_csv(P / f)
        p = d.p_value.to_numpy(float)
        ks = sps.kstest(p, "uniform")
        bonf = 0.05 / len(p)
        rows.append({"tokeniser": tok, "n_words": len(p), "n_langs": d.lang.nunique(),
                     "n_conditions": d.condition.nunique(),
                     "draws_per_word": int(d.n_samples.min()), "total_draws": int(d.n_samples.sum()),
                     "n_segmentations_min": int(d.n_segmentations.min()),
                     "n_segmentations_max": int(d.n_segmentations.max()),
                     "p_min": p.min(), "p_median": float(pd.Series(p).median()), "p_max": p.max(),
                     "n_below_nominal_05": int((p < 0.05).sum()), "bonferroni_threshold": bonf,
                     "n_below_bonferroni": int((p < bonf).sum()),
                     "ks_D": float(ks.statistic), "ks_p": float(ks.pvalue)})
    return pd.DataFrame(rows)


def run() -> None:
    vocab_by_script().to_csv(TABLES / "xlmr_vocab_by_script.csv", index=False)
    vocab_sizes().to_csv(TABLES / "tokeniser_vocab_sizes.csv", index=False)
    panel_tp_summary().to_csv(TABLES / "tokeniser_panel_tp_summary.csv", index=False)
    sampler_uniformity_ks().to_csv(TABLES / "sampler_uniformity_ks.csv", index=False)
    rt = pd.read_csv(P / "wmt_roundtrip.csv")
    rt[["lang", "roundtrip_ok_of_60"]].to_csv(TABLES / "xlmr_roundtrip_by_lang.csv", index=False)
    tp = pd.read_csv(P / "wmt_token_parity.csv")
    tp[tp.basis == "first120"][["setting", "token_parity"]].to_csv(
        TABLES / "wmt_token_parity_first120.csv", index=False)
    tp.to_csv(TABLES / "wmt_token_parity_full.csv", index=False)
    for f in ["sampler_uniformity", "sampler_uniformity_mt5", "tcr_consistency",
              "morphscore_gate", "nbsp_sensitivity", "intrinsic_indicmt"]:
        pd.read_csv(P / f"{f}.csv").to_csv(TABLES / f"{f}.csv", index=False)


if __name__ == "__main__":
    run()
